columns:
  ID: int
  LIMIT_BAL: int
  SEX: int
  EDUCATION: int
  MARRIAGE: int
  AGE: int
  PAY_0: int
  PAY_2: int
  PAY_3: int
  PAY_4: int
  PAY_5: int
  PAY_6: int
  BILL_AMT1: int
  BILL_AMT2: int
  BILL_AMT3: int
  BILL_AMT4: int
  BILL_AMT5: int
  BILL_AMT6: int
  PAY_AMT1: int
  PAY_AMT2: int
  PAY_AMT3: int
  PAY_AMT4: int
  PAY_AMT5: int
  PAY_AMT6: int
  default payment next month: int



dtypes:
  ID: "int64"
  LIMIT_BAL: "int64"
  SEX: int64
  EDUCATION: "int64"
  MARRIAGE: "int64"
  AGE: "int64"
  PAY_0: "int64"
  PAY_2: "int64"
  PAY_3: "int64"
  PAY_4: "int64"
  PAY_5: "int64"
  PAY_6: "int64"
  BILL_AMT1: "int64"
  BILL_AMT2: "int64"
  BILL_AMT3: "int64"
  BILL_AMT4: "int64"
  BILL_AMT5: "int64"
  BILL_AMT6: "int64"
  PAY_AMT1: "int64"
  PAY_AMT2: "int64"
  PAY_AMT3: "int64"
  PAY_AMT4: "int64"
  PAY_AMT5: "int64"
  PAY_AMT6: "int64"
  default payment next month: "int64"

numerical_columns:
  - ID
  - LIMIT_BAL
  - SEX
  - EDUCATION
  - MARRIAGE
  - AGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6
  - BILL_AMT1
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6
  - default payment next month

categorical_columns: []



  


column_rename:
  PAY_0: PAY_SEPT
  PAY_2: PAY_AUG
  PAY_3: PAY_JUL
  PAY_4: PAY_JUN
  PAY_5: PAY_MAY
  PAY_6: PAY_APR
  BILL_AMT1: BILL_AMT_SEPT
  BILL_AMT2: BILL_AMT_AUG
  BILL_AMT3: BILL_AMT_JUL
  BILL_AMT4: BILL_AMT_JUN
  BILL_AMT5: BILL_AMT_MAY
  BILL_AMT6: BILL_AMT_APR
  PAY_AMT1: PAY_AMT_SEPT
  PAY_AMT2: PAY_AMT_AUG
  PAY_AMT3: PAY_AMT_JUL
  PAY_AMT4: PAY_AMT_JUN
  PAY_AMT5: PAY_AMT_MAY
  PAY_AMT6: PAY_AMT_APR

column_rename2:
  PAY_0:
    name: PAY_SEPT
    dtype: int64
  PAY_2:
    name: PAY_AUG
    dtype: int64
  PAY_3:
    name: PAY_JUL
    dtype: int64
  PAY_4:
    name: PAY_JUN
    dtype: int64
  PAY_5:
    name: PAY_MAY
    dtype: int64
  PAY_6:
    name: PAY_APR
    dtype: int64
  BILL_AMT1:
    name: BILL_AMT_SEPT
    dtype: int64
  BILL_AMT2:
    name: BILL_AMT_AUG
    dtype: int64
  BILL_AMT3:
    name: BILL_AMT_JUL
    dtype: int64
  BILL_AMT4:
    name: BILL_AMT_JUN
    dtype: int64
  BILL_AMT5:
    name: BILL_AMT_MAY
    dtype: int64
  BILL_AMT6:
    name: BILL_AMT_APR
    dtype: int64
  PAY_AMT1:
    name: PAY_AMT_SEPT
    dtype: int64
  PAY_AMT2:
    name: PAY_AMT_AUG
    dtype: int64
  PAY_AMT3:
    name: PAY_AMT_JUL
    dtype: int64
  PAY_AMT4:
    name: PAY_AMT_JUN
    dtype: int64
  PAY_AMT5:
    name: PAY_AMT_MAY
    dtype: int64
  PAY_AMT6:
    name: PAY_AMT_APR
    dtype: int64


# for data transformation
num_features:
  - EDUCATION
  - MARRIAGE
  - PAY_0
  - PAY_2
  - PAY_3
  - PAY_4
  - PAY_5
  - PAY_6
  #- PAY_SEPT
  #- PAY_AUG
  #- PAY_JUL
  #- PAY_JUN
  #- PAY_MAY
  #- PAY_APR

or_columns: []  # columns to be ordinal encoded like ['SEX'/Gender] means Yes or No


oh_columns: []  # columns to be one hot encoded like EDUCATION', 'MARRIAGE']

transform_columns:
  - LIMIT_BAL
  - BILL_AMT1
  - BILL_AMT6
  - PAY_AMT1
  - PAY_AMT2
  - PAY_AMT3
  - PAY_AMT4
  - PAY_AMT5
  - PAY_AMT6
  #- BILL_AMT_SEPT
  #- BILL_AMT_APR
  #- PAY_AMT_SEPT
  #- PAY_AMT_AUG
  #- PAY_AMT_JUL
  #- PAY_AMT_JUN
  #- PAY_AMT_MAY
  #- PAY_AMT_APR

replace_invalid_values_in_columns:
- PAY_0
- PAY_2
- PAY_3
- PAY_4
- PAY_5
- PAY_6
#- PAY_SEPT
#- PAY_AUG  
#- PAY_JUL  
#- PAY_JUN 
#- PAY_MAY 
#- PAY_APR

drop_columns:
  - ID
  - SEX
  - AGE
  - BILL_AMT2
  - BILL_AMT3
  - BILL_AMT4
  - BILL_AMT5
  #- BILL_AMT_AUG
  #- BILL_AMT_MAY
  #- BILL_AMT_JUL
  #- BILL_AMT_JUN